### ISSUE TITLE
Error when saving -  [ERROR]: result.resolve is not a function

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#729]
_From @akershteyn on September 15, 2016 16:26_

Installed new MavensMate app v0.0.11-beta.3 on Windows 7
Connected to the project from MM app. 
Opened project in sublime-text editor. 
Tried to modify something save the changes
Getting following error:  
Timestamp: Thu, 15 Sep 2016 11:24:08
   Result: [ERROR]: result.resolve is not a function. 
I am getting this error regardless what i try to change/save

_Copied from original issue: joeferraro/MavensMate-Desktop#148_

**Comment by joeferraro** [comment]
_From @akershteyn on September 15, 2016 16:29_

the same message when trying refresh from server

**Comment by joeferraro** [comment]
_From @akershteyn on September 15, 2016 18:40_

Seems like the issue resolved by updating MM app setting:  

 **The full path of your Sublime Text executable (Sublime Text users only).** 

Mine was  "windows": "C:\\Program Files\\Sublime\\sublime_text.exe",    
vs  
default value ... \\Sublime text 3\\sublime_text.exe",    

working now.

**Comment by joeferraro** [comment]
@akershteyn oh wow, thanks for uncovering this. Re-opening as a bug

**Comment by akershteyn** [comment]
sure thing.

**Comment by anselmbradford** [comment]
This also happens if the Atom path is the default path and hasn't been updated to the actual path to the app.

**Comment by GithubTester001** [comment]
Updating path in MM global settings does not help in my case. Any ideas? See details below:
MM: 0.0.11-beta.7 | Atom: 1.16.0 | macOS: Sierra 10.12.4
The full path to atom executable (Atom users only)
"osx": "/Applications/Atom"
That is the actual app location but still receiving error on save:
result.resolve is not a function

**Comment by alimohammadsfd** [comment]
Was anyone able to resolve this issue?
